### ISSUE TITLE
Markdown not rendering properly on the docs website

### ISSUE THREAD

**Issue by kranurag7** [kubecost/docs#271]
This issue is with respect to the getting started [page](https://guide.kubecost.com/hc/en-us/articles/4407595947799-Getting-Started) If we look at the cost optimization section on this page then it's confusing to me. With too many numbers and prices floating around, it's very easy to get confused and one have to repeat the reading. Overall, for me, I have to read it thrice to get it. 

![Screenshot from 2022-06-16 21-56-52](https://user-images.githubusercontent.com/81210977/174121596-dd62c0f7-fc7e-49fe-aec4-c8af28ec1436.png)
The same document is much easier to read on the GitHub page. 

![Screenshot from 2022-06-16 22-02-38](https://user-images.githubusercontent.com/81210977/174121914-798b0328-c148-422e-9cb3-0f3c2ddef432.png)

- I think the problem is arising because the markdown is not rendering properly on the website. 

### Proposed solution
- We can add a diagram to make things more clear, and with visuals it will be much easier to understand without getting distracted. 
- If not diagram then we can add math blocks support which GitHub recently [launched](https://github.blog/2022-05-19-math-support-in-markdown/) and with that the equation will look like this on the github page 

$ ((0.5/2) * 20 + (0.5/1) * 1) / (20 + 1) = 5.5 / 21 = 26% 2 $

- I'm not sure how this will look like on the main docs website. 

gz#2000<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2000'>Zendesk ticket #2000</a>)</i>

**Comment by kranurag7** [comment]
codeblocks, backticks and links are not rendering as well.

**Comment by kbrwn** [comment]
@kranurag7 Thanks for reporting this. This page was recently updated to use `<details></details>` html tags to create drop down menus which does not render then same on guide.kubecost.com as github currently. We will work on getting this updated to be properly formatted.

**Comment by bwhaley** [comment]
Semi-related - I also noticed that expanding the sections on the left of the docs site and then clicking one of the subheadings will then collapse the section again. This makes for a disjointed reading experience because you need to constantly expand a section, find the subheading, click, read, repeat with the next subheading.

**Comment by nealormsbee** [comment]
Hi folks 👋 

We're looking at fully transitioning our documentation to a different platform for a smoother experience in the coming weeks. I don't have an exact timeline for you, but it will be sooner than later, and we hope to address these formatting issues and more. Thanks for bearing with us in the meantime.

@teevans I've added this issue to the Frontend-Team backlog, because I believe our group is taking over docs presentation. Will leave to your discretion whether a separate project or other labeling is warranted.

**Comment by bstuder99** [comment]
Docs page looks a lot nicer now https://docs.kubecost.com/using-kubecost/getting-started
