### ISSUE TITLE
Event triggers and notifications docs 

### ISSUE THREAD

**Issue by Adam-Stack-PM** [kubecost/docs#304]
Create a complete list of both internal and external event triggers and notifications. Then determine if there are additional items we would like to add. 

**Related Issues** 
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1319
https://github.com/opencost/opencost/issues/264
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1252

**Related PRs**
https://github.com/kubecost/kubecost-cost-model/pull/796
https://github.com/opencost/opencost/pull/1214
https://github.com/kubecost/kubecost-cost-model/pull/784

**Comment by Adam-Stack-PM** [comment]
@sundeepghuman Possible documentation catchup work from past releases.

**Comment by Adam-Stack-PM** [comment]
@bstuder99 possible doc opportunity for you when you have time.

**Comment by bstuder99** [comment]
Ok, I'll have to table this for now but let me revisit this in a few days.

**Comment by bstuder99** [comment]
@kwombach12 @dwbrown2 Revisiting this issue after several months. At the moment the stated metrics found in the related PRs/issues are:
* kubecost_http_requests_total [Counter]: Total number of http requests serviced.
* kubecost_http_response_time_seconds [Histogram]: Response time in seconds.
* kubecost_http_response_size_bytes [Summary]: Response size in bytes.
We may need to possibly rename these for OpenCost due to CNCF having rules about it. Anyways, looking for some clarification on what else needs to be added for. @nikovacevic and I are hoping for some clarification on what is meant by "internal and external" notifications. All metrics can probably be added https://www.opencost.io/docs/prometheus

**Comment by bstuder99** [comment]
https://github.com/opencost/opencost-website/pull/96/files
