### ISSUE TITLE
Docs light mode gone?

### ISSUE THREAD

**Issue by ian-lmcb** [kubecost/docs#614]
Seems the Kubecost docs gitbook is now forced to a dark mode theme. I could swear it used to be a light theme. There appears to be no toggle to switch though.

This doesn't prevent me from reading the docs but it has been driving me crazy for the last while since this change occurred.

Was this an intentional change? Is there supposed to be a toggle?

**Comment by dwbrown2** [comment]
+1! Do we know what changed?

**Comment by bstuder99** [comment]
Hi Ian. This change was intentional, making use of GitBook's customization options. While the docs could be considered similar to dark mode, it is actually an intentional palette choice here. GitBook has limited color options, including hyperlink colors which in a previous version were not that visible, blending in with the regular body text. Light mode and dark mode are only able to be toggled internally, and only the selected version will appear on the frontend. I can put in a request with GitBook's support to see if a switch between light and dark mode can be allowed on the client side, but for now, dark mode is the default and cannot be changed on an individual level.

**Comment by dwbrown2** [comment]
I find it harder to read as a user. Did you consider other color options?

**Comment by bstuder99** [comment]
Yes, we debated this internally. Part of this issue comes from hyperlink visibility. In a default palette, our banner color (a dark green fitting brand standards) would also be sampled for hyperlink colors, making them hard to find compared to the dark body text. This required switching to a light mode or dark mode, using a brighter green color that would not be used for the banner (the same color as our logo, which would also affect visibility). Overall, team members preferred dark mode over light mode.

**Comment by ian-lmcb** [comment]
Gotcha.

Yes please on that request to gitbooks for a toggle. I won't get my hopes up but I do find it hard to use the docs now during the day so would be nice to have the option if they can provide it.

**Comment by bstuder99** [comment]
I agree, we have put in other feature requests in the past, but I will update this thread with their response when I hear back before I close the thread.

**Comment by bstuder99** [comment]
Response from GitBook support:
>Hi Brett,
>Thank you for contacting us.
We are aware that this can be fairly frustrating - sorry to hear you had some issues with that.
We are working on shipping this feature in around 1-2 months' time. Please keep your eyes out for our [changelog](https://changelog.gitbook.com/april-2023/5-april-23-gitbook-ai-and-lens-preview-your-change-requests-and-more) for the latest updates.
>Please let me know if I can help further!
>Thanks,
Natasza

For now, I hope you can make use of our current docs palette. I will look to implement client-side switching between light/dark mode as soon as it becomes available.

**Comment by bstuder99** [comment]
Thanks for your patience Ian. Just posting to let you know we have implemented a toggle switch between light and dark mode for docs.kubecost.com.

**Comment by ian-lmcb** [comment]
Awesome, I'll be making use of that right away! Thanks for following up!
