### ISSUE TITLE
Add instructions for setting up the Athena Database and Table

### ISSUE THREAD

**Issue by FrederikNS** [kubecost/docs#91]
The AWS Cloud Integration explains that you have to supply the Athena Database and Table, and explains that these were created in the `Step 2: Setting up the CUR`, however `Setting up the CUR` is actually `Step 1`, and additionally that step never details how to set up the database and table. The following `Step 2: Setting up Athena` also doesn't detail how to create this database and table.

https://github.com/kubecost/docs/blob/6f5bc36a05cdc4dfed66e4b32769bd06149cccfc/aws-cloud-integrations.md#L376-L379

I'm not sure if these databases and tables are supposed to be automatically created, or whether I need to create them manually, and which settings to set them up with.

Could this be clarified in the documentation?

**Comment by dwbrown2** [comment]
I agree that this needs to be corrected and also clarified. 

@AjayTripathy is this created as part of "Setting up Athena"?

Any chance you would be able to update docs?

**Comment by FrederikNS** [comment]
Has there been any progress on this?

**Comment by kirbsauce** [comment]
Apologies for the delayed action on this issue.  You're correct, there are some inaccuracies.  The settings you're referring to should be related to the Athena setup, as opposed to the CUR setup.  I'll be working on some doc updates.  

Thanks for taking the time to contribute to the improvement of our user experience and, again, sorry for the delay.

**Comment by AjayTripathy** [comment]
Hi @MarjanJordanovski you can check the /assets.html page in the community edition of kubecost to view cloud asset data.

Closing out this issue since the documentation has been updated and should be usable, but feel free to reach out to us on our regular support channels if you have further questions! https://join.slack.com/t/kubecost/shared_invite/enQtNTA2MjQ1NDUyODE5LWFjYzIzNWE4MDkzMmUyZGU4NjkwMzMyMjIyM2E0NGNmYjExZjBiNjk1YzY5ZDI0ZTNhZDg4NjlkMGRkYzFlZTU
